//! WIT contract crate for savvagent external plugins (sub-project D).
//!
//! This crate is intentionally a documentation-and-resources leaf: it owns
//! the `.wit` files that describe the three external-plugin worlds
//! (`plugin-static`, `plugin-interactive`, `plugin-provider`) and ships
//! them as crate-relative resources for downstream consumers.
//!
//! ## Why no `wit_bindgen::generate!` here
//!
//! `wit-bindgen` is a *guest*-side code generator: it produces the bindings
//! a WASM component links against to satisfy its imports/exports. Plugin
//! authors depend on `wit-bindgen` from their own crate; this crate would
//! gain nothing by invoking the macro on the host build.
//!
//! Host-side bindings (the types and `bindgen!`-generated traits the host
//! linker uses to satisfy a component's imports) live in
//! `savvagent-plugin-wasm` (Task 2), generated by
//! `wasmtime::component::bindgen!` against the `.wit` files in this crate.
//! That keeps wasmtime, tokio, reqwest, and the rest of the runtime out of
//! this crate — see `.github/workflows/wit-dep-guard.yml`.
//!
//! ## Where to find things
//!
//! - `wit/shared.wit` — shared interface (effects, manifest, hook kinds,
//!   key events, theme colors, styled spans, errors).
//! - `wit/spp.wit` — SPP types mirroring `savvagent-protocol`
//!   (CompleteRequest/Response, streaming events, provider errors).
//! - `wit/plugin-static.wit`, `wit/plugin-interactive.wit`,
//!   `wit/plugin-provider.wit` — the three plugin worlds (skeletons in
//!   Task 1; filled in Task 2).

#![forbid(unsafe_code)]

// The `.wit` files in `../wit/` are the canonical source of truth for this
// crate. They are not included as rustdoc via `include_str!` because raw
// WIT contains indented blocks that rustdoc would parse as Rust doctests
// and reject. Browse the files directly under
// `crates/savvagent-plugin-wit/wit/`.

/// Absolute-at-build-time path to this crate's `wit/` directory. Downstream
/// crates (notably `savvagent-plugin-wasm` once it lands in Task 2) use
/// this to point `wasmtime::component::bindgen!` at the canonical WIT
/// source without having to hard-code a workspace-relative path.
///
/// Exposed as a `&'static str` so it can be used in `concat!` and macro
/// `path:` arguments. Resolved via `CARGO_MANIFEST_DIR`, which Cargo sets
/// during `build.rs` and proc-macro invocations.
pub const WIT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/wit");
